name: "Automation tests"

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Common Setup
        uses: ./.github/actions/common-setup
      - name: Install dependencies
        run: pnpm install
      - name: Install Playwright Browsers
        run: pnpm playwright install --with-deps chromium
      - name: Setup env
        uses: ./.github/actions/setup-env
        env:
          VITE_WEATHER_KEYS: ${{ secrets.VITE_WEATHER_KEYS }}
          VITE_WEATHER_API: ${{ secrets.VITE_WEATHER_API }}
      - name: Build extension for tests
        run: pnpm build
      - name: Run Playwright tests
        run: pnpm e2e
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
