name: "Automation tests"

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  vitest:
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "pnpm"

      - name: Enable pnpm via corepack
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate

      - name: Install dependencies
        run: pnpm install
      - name: Run vitest
        run: pnpm vitest
