name: "Automation tests"

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  vitest:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/common-setup
      - name: Run vitest
        run: pnpm vitest

  playwright-ct:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/common-setup
      - name: Install Playwright Browsers
        run: pnpm playwright install --with-deps chromium firefox
      - name: Build Extension
        run: PARCEL_WORKER_BACKEND=process pnpm build
      - name: Run Playwright tests
        run: pnpm e2e:ct

  playwright:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/common-setup
      - name: Install Playwright Browsers
        run: pnpm playwright install --with-deps chromium
      - uses: ./.github/actions/setup-env
        env:
          PLASMO_PUBLIC_WALLPAPER_API: ${{ secrets.PLASMO_PUBLIC_WALLPAPER_API }}
          PLASMO_PUBLIC_WEATHER_API_KEYS: ${{ secrets.PLASMO_PUBLIC_WEATHER_API_KEYS }}
      - name: Build Extension
        run: PARCEL_WORKER_BACKEND=process pnpm build
      - name: Run Playwright tests
        run: pnpm e2e
