name: "Build Startify Extension"
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:

  build-extensions:
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    strategy:
      matrix:
        target:
          - chrome
          - firefox-mv3
          - firefox-mv2
        env_file:
          - .env.chrome
          - .env.firefox
          - .env.firefox
      exclude:
        - target: chrome
          env_file: .env.firefox
    steps:
      - uses: actions/checkout@v4
      - name: Cache pnpm modules
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: true
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "pnpm"
      - name: Build and zip extension for ${{ matrix.target }}
        run: pnpm plasmo build --zip --hoist --target=${{ matrix.target }} --env=${{ matrix.env_file }}
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}-build
          path: build
