name: "Build Startify Extension"
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        target: [chrome-mv3, firefox-mv3, firefox-mv2]
    steps:
      - uses: actions/checkout@v4
      - name: Common Setup
        uses: ./.github/actions/common-setup
      - name: Setup env
        uses: ./.github/actions/setup-env
        env:
          PLASMO_PUBLIC_WALLPAPER_API: ${{ secrets.PLASMO_PUBLIC_WALLPAPER_API }}
          PLASMO_PUBLIC_WEATHER_API_KEYS: ${{ secrets.PLASMO_PUBLIC_WEATHER_API_KEYS }}
      - name: Build extension
        run: PARCEL_WORKER_BACKEND=process pnpm plasmo build --target=${{ matrix.target }}
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}-prod
          path: build/${{ matrix.target }}-prod
          retention-days: 7
