name: "Build Startify Extension"
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  lint:
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "pnpm"
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest
      - name: Cache pnpm modules
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - name: Install dependencies
        run: pnpm install
      - name: Run lint
        run: pnpm lint

  build-chrome:
    needs: lint
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - name: Cache pnpm modules
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: true
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "pnpm"
      - name: Setup env
        uses: ./.github/actions/setup-env
        env:
          VITE_WEATHER_KEYS: ${{ secrets.VITE_WEATHER_KEYS }}
      - name: Build and zip Chrome extension
        run: pnpm zip
      - uses: actions/upload-artifact@v4
        with:
          name: chrome-mv3
          path: .output/*-chrome.zip

  build-firefox:
    needs: lint
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - name: Cache pnpm modules
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: true
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "pnpm"
      - name: Setup env
        uses: ./.github/actions/setup-env
        env:
          VITE_WEATHER_KEYS: ${{ secrets.VITE_WEATHER_KEYS }}
      - name: Build and zip Firefox extension
        run: pnpm zip:firefox
      - uses: actions/upload-artifact@v4
        with:
          name: firefox-mv3
          path: |
            .output/*-firefox.zip
            .output/*-sources.zip
