name: "Build Startify Extension"
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  lint:
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Install dependencies
        run: npm ci
      - name: Run lint
        run: npm run lint

  build-chrome:
    needs: lint
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm ci

      - name: Setup env
        uses: ./.github/actions/setup-env
        env:
          VITE_WEATHER_KEYS: ${{ secrets.VITE_WEATHER_KEYS }}

      - name: Build and zip Chrome extension
        run: npm run zip

      - uses: actions/upload-artifact@v4
        with:
          name: chrome-mv3
          path: .output/*-chrome.zip

  build-firefox:
    needs: lint
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm ci

      - name: Setup env
        uses: ./.github/actions/setup-env
        env:
          VITE_WEATHER_KEYS: ${{ secrets.VITE_WEATHER_KEYS }}

      - name: Build and zip Firefox extension
        run: npm run zip:firefox

      - uses: actions/upload-artifact@v4
        with:
          name: firefox-mv3
          path: |
            .output/*-firefox.zip
            .output/*-sources.zip
