name: "Build Startify Extension"
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  lint:
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - name: Common Setup
        uses: ./.github/actions/common-setup
      - name: Run lint
        run: pnpm lint

  build-chrome:
    needs: lint
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - name: Common Setup
        uses: ./.github/actions/common-setup
      - name: Setup env
        uses: ./.github/actions/setup-env
        env:
          VITE_WEATHER_KEYS: ${{ secrets.VITE_WEATHER_KEYS }}
      - name: Build and zip Chrome extension
        run: pnpm zip
      - uses: actions/upload-artifact@v4
        with:
          name: chrome-mv3
          path: .output/*-chrome.zip

  build-firefox:
    needs: lint
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - name: Common Setup
        uses: ./.github/actions/common-setup
      - name: Setup env
        uses: ./.github/actions/setup-env
        env:
          VITE_WEATHER_KEYS: ${{ secrets.VITE_WEATHER_KEYS }}
      - name: Build and zip Firefox extension
        run: pnpm zip:firefox
      - uses: actions/upload-artifact@v4
        with:
          name: firefox-mv3
          path: |
            .output/*-firefox.zip
            .output/*-sources.zip
