name: "Build Startify Extension"
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-chrome:
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - name: Cache pnpm modules
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: true
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "pnpm"
      - name: Build and zip Chrome extension
        run: pnpm plasmo build --zip --hoist --env=.env.chrome
      - uses: actions/upload-artifact@v4
        with:
          name: chrome-mv3
          path: build/chrome-mv3-prod

  build-firefox-mv3:
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - name: Cache pnpm modules
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: true
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "pnpm"
      - name: Build and zip Firefox MV3 extension
        run: pnpm plasmo build --zip --hoist --target=firefox-mv3 --env=.env.firefox
      - uses: actions/upload-artifact@v4
        with:
          name: firefox-mv3
          path: build/firefox-mv3-prod

  build-firefox-mv2:
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - name: Cache pnpm modules
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: true
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "pnpm"
      - name: Build and zip Firefox MV2 extension
        run: pnpm plasmo build --zip --hoist --target=firefox-mv2 --env=.env.firefox
      - uses: actions/upload-artifact@v4
        with:
          name: firefox-mv2
          path: build/firefox-mv2-prod
