name: "Lint Check"
on:
  push:
    branches-ignore:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Common Setup
        uses: ./.github/actions/common-setup
      - name: Install dependencies
        run: pnpm install
      - name: Check code
        run: pnpm lint
      - name: Lint code
        run: pnpm lint
