name: "Release Startify Extension"
on:
  push:
    tags:
      - v*.*.*

permissions:
  contents: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Common Setup
        uses: ./.github/actions/common-setup
      - name: Install dependencies
        run: pnpm install
      - name: Check code
        run: pnpm lint
      - name: Lint code
        run: pnpm lint

  vitest:
    needs: lint
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - name: Common Setup
        uses: ./.github/actions/common-setup
      - name: Install dependencies
        run: pnpm install
      - name: Vitest
        run: pnpm vitest

  playwright:
    needs: lint
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Common Setup
        uses: ./.github/actions/common-setup
      - name: Install dependencies
        run: pnpm install
      - name: Install Playwright Browsers
        run: pnpm playwright install --with-deps chromium
      - name: Setup env
        uses: ./.github/actions/setup-env
        env:
          VITE_WEATHER_KEYS: ${{ secrets.VITE_WEATHER_KEYS }}
          VITE_WEATHER_API: ${{ secrets.VITE_WEATHER_API }}
      - name: Build extension for tests
        run: pnpm build
      - name: Run Playwright tests
        run: pnpm e2e
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

  release:
    needs: [playwright, vitest]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Common Setup
        uses: ./.github/actions/common-setup
      - name: Install dependencies
        run: pnpm install
      - name: Setup env
        uses: ./.github/actions/setup-env
        env:
          VITE_WEATHER_KEYS: ${{ secrets.VITE_WEATHER_KEYS }}
          VITE_WEATHER_API: ${{ secrets.VITE_WEATHER_API }}
      - name: Zip extensions
        run: |
          pnpm zip
          pnpm zip:firefox
      - name: Submit to stores
        run: |
          pnpm wxt submit \
            --chrome-zip .output/*-chrome.zip \
            --firefox-zip .output/*-firefox.zip --firefox-sources-zip .output/*-sources.zip
        env:
          CHROME_EXTENSION_ID: ${{ secrets.CHROME_EXTENSION_ID }}
          CHROME_CLIENT_ID: ${{ secrets.CHROME_CLIENT_ID }}
          CHROME_CLIENT_SECRET: ${{ secrets.CHROME_CLIENT_SECTER }}
          CHROME_REFRESH_TOKEN: ${{ secrets.CHROME_REFRESH_TOKEN }}
          FIREFOX_EXTENSION_ID: ${{ secrets.FIREFOX_EXTENSION_ID }}
          FIREFOX_JWT_ISSUER: ${{ secrets.FIREFOX_API_KEY }}
          FIREFOX_JWT_SECRET: ${{ secrets.FIREFOX_API_SECRET }}

      - name: Submit to github
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: |
            .output/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
