name: "Release Startify Extension"
on:
  # push:
  #   tags:
  #     - v*.*.*
  workflow_dispatch:

permissions:
  contents: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm lint

  vitest:
    needs: lint
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Vitest
        run: pnpm vitest

      # - name: Zip extensions
      #   run: |
      #     pnpm zip
      #     pnpm zip:firefox

      # - name: Submit to stores
      #   run: |
      #     pnpm wxt submit \
      #       --chrome-zip .output/*-chrome.zip \
      #       --firefox-zip .output/*-firefox.zip --firefox-sources-zip .output/*-sources.zip
      #   env:
      #     CHROME_EXTENSION_ID: ${{ secrets.CHROME_EXTENSION_ID }}
      #     CHROME_CLIENT_ID: ${{ secrets.CHROME_CLIENT_ID }}
      #     CHROME_CLIENT_SECRET: ${{ secrets.CHROME_CLIENT_SECTER }}
      #     CHROME_REFRESH_TOKEN: ${{ secrets.CHROME_REFRESH_TOKEN }}
      #     FIREFOX_EXTENSION_ID: ${{ secrets.FIREFOX_EXTENSION_ID }}
      #     FIREFOX_JWT_ISSUER: ${{ secrets.FIREFOX_API_KEY }}
      #     FIREFOX_JWT_SECRET: ${{ secrets.FIREFOX_API_SECRET }}
