name: "Release Startify Extension"
on:
  push:
    tags:
      - v*.*.*

permissions:
  contents: write

jobs:
  lint:
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - name: Common Setup
        uses: ./.github/actions/common-setup
      - name: Run lint
        run: pnpm eslint .

  vitest:
    needs: lint
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - name: Common Setup
        uses: ./.github/actions/common-setup
      - name: Run vitest
        run: pnpm vitest

  playwright-ct:
    needs: lint
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - name: Common Setup
        uses: ./.github/actions/common-setup
      - name: Install Playwright Browsers
        run: pnpm playwright install
      - name: Run Playwright tests
        run: pnpm e2e:ct

  playwright:
    needs: lint
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - name: Common Setup
        uses: ./.github/actions/common-setup
      - name: Install Playwright Browsers
        run: pnpm playwright install --with-deps chromium
      - name: Setup env
        uses: ./.github/actions/setup-env
        env:
          PLASMO_PUBLIC_WALLPAPER_API: ${{ secrets.PLASMO_PUBLIC_WALLPAPER_API }}
          PLASMO_PUBLIC_WEATHER_API_KEYS: ${{ secrets.PLASMO_PUBLIC_WEATHER_API_KEYS }}
      - name: Build Extension
        run: PARCEL_WORKER_BACKEND=process pnpm build
      - name: Run Playwright tests
        run: pnpm e2e

  release_chrome:
    needs: [vitest, playwright, playwright-ct]
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - name: Common Setup
        uses: ./.github/actions/common-setup
      - name: Setup env
        uses: ./.github/actions/setup-env
        env:
          PLASMO_PUBLIC_WALLPAPER_API: ${{ secrets.PLASMO_PUBLIC_WALLPAPER_API }}
          PLASMO_PUBLIC_WEATHER_API_KEYS: ${{ secrets.PLASMO_PUBLIC_WEATHER_API_KEYS }}
      - name: Build and zip Chrome extension
        run: PARCEL_WORKER_BACKEND=process pnpm build --zip --env=.env.chrome
      - name: Upload to Chrome Web Store
        uses: mobilefirstllc/cws-publish@latest
        with:
          action: "publish"
          client_id: ${{ secrets.CHROME_CLIENT_ID }}
          client_secret: ${{ secrets.CHROME_CLIENT_SECTER }}
          refresh_token: ${{ secrets.CHROME_REFRESH_TOKEN }}
          extension_id: "fjjipcmebaelmnkkbdjnhhjbgenecgbd"
          zip_file: "build/chrome-mv3-prod.zip"

  release_firefox:
    needs: [vitest, playwright, playwright-ct]
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - name: Common Setup
        uses: ./.github/actions/common-setup
      - name: Setup env
        uses: ./.github/actions/setup-env
        env:
          PLASMO_PUBLIC_WALLPAPER_API: ${{ secrets.PLASMO_PUBLIC_WALLPAPER_API }}
          PLASMO_PUBLIC_WEATHER_API_KEYS: ${{ secrets.PLASMO_PUBLIC_WEATHER_API_KEYS }}
      - name: Build and zip Firefox MV3 extension
        run: PARCEL_WORKER_BACKEND=process pnpm build --zip --target=firefox-mv3 --env=.env.firefox
      - name: Upload to Mozilla Add-ons
        uses: wdzeng/firefox-addon@v1
        with:
          addon-guid: "{d5e5fe42-da08-4573-8ffd-6075ae68c834}"
          xpi-path: build/firefox-mv3-prod.zip
          jwt-issuer: ${{ secrets.FIREFOX_API_KEY }}
          jwt-secret: ${{ secrets.FIREFOX_API_SECRET }}

  release_github:
    needs: [vitest, playwright, playwright-ct]
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - name: Common Setup
        uses: ./.github/actions/common-setup
      - name: Setup env
        uses: ./.github/actions/setup-env
        env:
          PLASMO_PUBLIC_WALLPAPER_API: ${{ secrets.PLASMO_PUBLIC_WALLPAPER_API }}
          PLASMO_PUBLIC_WEATHER_API_KEYS: ${{ secrets.PLASMO_PUBLIC_WEATHER_API_KEYS }}
      - name: Build and zip extensions
        run: |
          PARCEL_WORKER_BACKEND=process pnpm build --zip --env=.env.chrome
          PARCEL_WORKER_BACKEND=process pnpm build --zip --target=firefox-mv3 --env=.env.firefox
          PARCEL_WORKER_BACKEND=process pnpm build --zip --target=firefox-mv2 --env=.env.firefox
      - name: Release on GitHub (Firefox MV2)
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: |
            build/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
