name: "Create Startify Extension"
on:
  push:
    tags:
      - v*.*.*

permissions:
  contents: write

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - name: Cache pnpm modules
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: true
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "pnpm"
      - name: Run lint
        run: pnpm eslint .

  vitest:
    needs: lint
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - name: Cache pnpm modules
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: true
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "pnpm"
      - name: Run vitest
        run: pnpm vitest

  playwright:
    needs: lint
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - name: Cache pnpm modules
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: true
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "pnpm"
      - name: Install Playwright Browsers
        run: pnpm playwright install --with-deps chromium
      - name: Build Extension
        run: pnpm build
      - name: Run Playwright tests
        run: pnpm e2e

  release:
    needs: [vitest, playwright]
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - name: Cache pnpm modules
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: true
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "pnpm"
      - name: Build Next App
        run: pnpm build:next
      - name: Build and zip extensions
        run: |
          pnpm build:plasmo --zip
          pnpm build:plasmo --zip --target=firefox-mv3
          pnpm build:plasmo --zip --target=firefox-mv2
      - name: release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: |
            build/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
